import './globals.scss'
import { Ubuntu } from 'next/font/google'
import Layout from '../components/Layout.component'
import React, { ReactNode } from 'react';

const ubuntu = Ubuntu({
  weight: ['400'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="es">
      <body className={ubuntu.className}>
          <Layout>
            {children}
          </Layout>
      </body>
    </html>
  )
}
